Allow additional info key values
vitalik/django-ninja pull request #715
Opened 2023-03-26 14:10 UTC by chenatlas

Hey @vitalik! Thanks for your previous feedback and I totally get not being locked into an engine.
I wonder what do you think about this solution?
adding `additional_info` as optional to initialize the API, so users can pass whatever they need to extend the OpenAPI 'info' section.
 
for example:
```Python
api = NinjaAPI(
               version="1.0.0",
               additional_info={'x-logo': {'url': 'https://example.com/logo.svg'}},
               title="Demo API",
               description="This is a demo API with dynamic OpenAPI info section")
```

2023-05-03 02:56 UTC, SmileyChris commented
A nice simple addition. Bikeshedding the name, potentially this should be `openapi_info` to indicate that it's openAPI related.

Looks good, but could do with a test and docs. 👍🏻

2023-05-03 03:02 UTC, baseplate-admin requested changes
LGTM, Please add test and documentation

2023-05-06 20:04 UTC, chenatlas commented
@baseplate-admin / @SmileyChris done both, added testing, renamed to openapi_info and added docs.

2023-05-08 05:10 UTC, SmileyChris requested changes

2023-05-08 05:10 UTC, SmileyChris commented on docs/docs/guides/api-docs.md
> ->>> '/api/docs'
I think this should stay, it's showing the output of the reverse

2023-05-08 05:12 UTC, SmileyChris commented on ninja/main.py
> +        openapi_info: Optional[Dict[str, Any]] = {},
(And this comment got left out of my review?)

This should technically go last in case anyone is crazy enough to be using positional arguments. It makes more sense here though, so the better fix is enforcing these to be keyword arguments by adding `*,` on the previous line.

2023-05-08 08:31 UTC, chenatlas commented
@SmileyChris fixed, moved openapi_info to last and reverted the emitted line.

2023-05-27 11:54 UTC, merged

2023-05-27 12:23 UTC, vitalik commented
Hi @chenatlas thank you for contribution, this is merged, but I extended functionality to support other extra open api attributes (not just `info`)

this is how updating info should work now:
```PY
api = NinjaAPI(
   openapi_extra={
            "info": {
                "termsOfService": "https://example.com/terms/",
            }
        }
       
   },
```

2023-07-13 12:28 UTC, joaoflaviosantos commented
Hello @vitalik!

Is it possible to include extra schemas (not related to a specific route)? For example, as below?

```python
api = NinjaAPI(
    openapi_extra={
        "components": {
            "schemas": {
                "TestSchema": {
                    "title": "TestSchema",
                    "type": "object",
                    "properties": {
                        "cod_test": {"title": "Cód. test", "type": "integer"},
                        "test": {
                            "title": "Test",
                            "maxLength": 30,
                            "type": "string",
                        },
                    },
                    "required": ["cod_test", "test"],
                },
            }
        }
    }
)
```

Or using Schemas/model Schemas directly:

```python
api = NinjaAPI(
    openapi_extra={
        "components": {
            "schemas": {
                "TestSchema": TestSchema().dict(),
            }
        }
    }
)
```

Thanks in advance for the help!